[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
escrow_donate = "H4iPvKUYFtdis612fUaL8dxVD4HQF73YD2r4dsRYZL6P"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/ascespool/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
